services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./data:/app/data
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      GOOSE_DRIVER: ${GOOSE_DRIVER}
      GOOSE_DBSTRING: ${GOOSE_DBSTRING}
      GOOSE_MIGRATION_DIR: ${GOOSE_MIGRATION_DIR}
      GOOSE_TABLE: ${GOOSE_TABLE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_EMBEDDINGS_MODEL: ${OPENAI_EMBEDDINGS_MODEL}
      EMBEDDINGS_MODEL_DIM: ${EMBEDDINGS_MODEL_DIM}
      SEARCH_TOP_K: ${SEARCH_TOP_K}
      CORS_ORIGINS: ${CORS_ORIGINS}
      RATE_LIMIT_RPS: ${RATE_LIMIT_RPS}
      JWT_SECRET: ${JWT_SECRET}
      JWT_TTL: ${JWT_TTL}
      ADMINS: ${ADMINS}
    