services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./data:/app/data
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      GOOSE_DRIVER: ${GOOSE_DRIVER}
      GOOSE_DBSTRING: ${GOOSE_DBSTRING}
      GOOSE_MIGRATION_DIR: ${GOOSE_MIGRATION_DIR}
      GOOSE_TABLE: ${GOOSE_TABLE}
      CORS_ORIGINS: ${CORS_ORIGINS}
      RATE_LIMIT_RPS: ${RATE_LIMIT_RPS}
      JWT_SECRET: ${JWT_SECRET}
      JWT_TTL: ${JWT_TTL}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_NAME: ${ADMIN_NAME}
    